global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "gateway"
    static_configs:
      - targets: ["gateway:8080"]
    metrics_path: /metrics

  - job_name: "db-service"
    static_configs:
      - targets: ["db-service:4001"]
    metrics_path: /metrics

  - job_name: "auth-service"
    static_configs:
      - targets: ["auth-service:4002"]
    metrics_path: /metrics

  - job_name: "notification-service"
    static_configs:
      - targets: ["notification-service:4003"]
    metrics_path: /metrics

  - job_name: "ai-service"
    static_configs:
      - targets: ["ai-service:4004"]
    metrics_path: /metrics

  - job_name: "payment-service"
    static_configs:
      - targets: ["payment-service:4005"]
    metrics_path: /metrics

  - job_name: "metrics-service"
    static_configs:
      - targets: ["metrics-service:4006"]
    metrics_path: /metrics
